replicaCount: 1

image:
  repository: traefik/whoami
  pullPolicy: IfNotPresent
  tag: v1.8.7

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 32Mi
